#!/usr/bin/env bash
# deploy-to-live.sh
#
# Pipeline: build assets locally → push current branch → open PR → merge PR →
#           pull main locally → SSH to prod → fetch/reset → composer/migrate/cache → queue restart.
#
# Usage:
#   ./deploy-to-live.sh           # interactive (asks before merge + before remote step)
#   ./deploy-to-live.sh --yes     # no prompts (CI / repeat use)
#   ./deploy-to-live.sh --skip-build   # skip npm build (assets already current)
#
# Requires:
#   - .env.deploy in repo root (gitignored). See .env.deploy.example.
#   - SSH key auth to the production server (no password in this script — ever).
#   - gh CLI authenticated with `repo` scope.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

# ---- args ----
AUTO_YES=0
SKIP_BUILD=0
for arg in "$@"; do
  case "$arg" in
    --yes|-y)        AUTO_YES=1 ;;
    --skip-build)    SKIP_BUILD=1 ;;
    -h|--help)       sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown arg: $arg"; exit 2 ;;
  esac
done

confirm() {
  [ "$AUTO_YES" = 1 ] && return 0
  read -r -p "$1 [y/N] " ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

step() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ---- load config ----
[ -f .env.deploy ] || fail ".env.deploy missing. Copy .env.deploy.example and fill it in."
set -a; source .env.deploy; set +a

: "${DEPLOY_HOST:?DEPLOY_HOST not set in .env.deploy}"
: "${DEPLOY_USER:?DEPLOY_USER not set in .env.deploy}"
: "${DEPLOY_PATH:?DEPLOY_PATH not set in .env.deploy}"
: "${DEPLOY_PORT:=22}"
: "${DEPLOY_BASE_BRANCH:=main}"
: "${REMOTE_PHP:=php}"
: "${REMOTE_COMPOSER:=composer}"
: "${ENABLE_MAINTENANCE_MODE:=0}"

# ---- pre-flight ----
step "Pre-flight checks"
command -v gh >/dev/null  || fail "gh CLI not found"
command -v ssh >/dev/null || fail "ssh not found"
gh auth status >/dev/null 2>&1 || fail "gh CLI not authenticated. Run: gh auth login"

CURRENT_BRANCH=$(git branch --show-current)
[ -z "$CURRENT_BRANCH" ]                       && fail "Detached HEAD — checkout a feature branch first."
[ "$CURRENT_BRANCH" = "$DEPLOY_BASE_BRANCH" ]  && fail "On $DEPLOY_BASE_BRANCH already; this script expects a feature branch."

git diff --quiet                || fail "Uncommitted changes in working tree."
git diff --cached --quiet       || fail "Staged but uncommitted changes."
ok "Branch: $CURRENT_BRANCH (clean)"

# ---- build assets ----
if [ "$SKIP_BUILD" = 0 ]; then
  step "Building assets (npm run build)"
  npm run build
  if ! git diff --quiet -- public/build 2>/dev/null || ! git diff --cached --quiet -- public/build 2>/dev/null; then
    git add public/build
    git commit -m "chore: build assets for deploy"
    ok "Committed asset rebuild."
  else
    ok "Assets unchanged."
  fi
else
  ok "Skipped asset build."
fi

# ---- push ----
step "Pushing $CURRENT_BRANCH to origin"
git push -u origin "$CURRENT_BRANCH"
ok "Pushed."

# ---- PR + merge ----
step "Opening / finding PR for $CURRENT_BRANCH → $DEPLOY_BASE_BRANCH"
PR_NUMBER=$(gh pr list --head "$CURRENT_BRANCH" --base "$DEPLOY_BASE_BRANCH" --state open --json number -q '.[0].number' || true)
if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
  PR_TITLE="Deploy $CURRENT_BRANCH ($(date +%Y-%m-%d\ %H:%M))"
  gh pr create \
    --base "$DEPLOY_BASE_BRANCH" \
    --head "$CURRENT_BRANCH" \
    --title "$PR_TITLE" \
    --body "Automated deploy from \`$CURRENT_BRANCH\`. Generated by deploy-to-live.sh." >/dev/null
  PR_NUMBER=$(gh pr list --head "$CURRENT_BRANCH" --base "$DEPLOY_BASE_BRANCH" --state open --json number -q '.[0].number')
  ok "Opened PR #$PR_NUMBER"
else
  ok "Reusing open PR #$PR_NUMBER"
fi

confirm "Merge PR #$PR_NUMBER into $DEPLOY_BASE_BRANCH now?" || fail "Aborted before merge."
gh pr merge "$PR_NUMBER" --merge --delete-branch || fail "PR merge failed (check CI / merge conflicts)."
ok "PR #$PR_NUMBER merged."

# ---- sync local main ----
step "Syncing local $DEPLOY_BASE_BRANCH"
git checkout "$DEPLOY_BASE_BRANCH"
git pull origin "$DEPLOY_BASE_BRANCH"
ok "Local $DEPLOY_BASE_BRANCH up to date."

# ---- remote deploy over SSH ----
confirm "SSH to ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PORT} and deploy now?" || { echo "Skipped remote deploy. Local main is synced; run again with --yes when ready."; exit 0; }

step "Deploying to ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_PORT}:${DEPLOY_PATH}"

# Heredoc executed on the remote. Local-side variables interpolate; use \$ for remote-only.
ssh -p "${DEPLOY_PORT}" -o StrictHostKeyChecking=accept-new "${DEPLOY_USER}@${DEPLOY_HOST}" bash -s <<REMOTE
set -euo pipefail

cd "${DEPLOY_PATH}" || { echo "DEPLOY_PATH not found on server: ${DEPLOY_PATH}"; exit 1; }

echo "→ git fetch + hard reset to origin/${DEPLOY_BASE_BRANCH}"
git fetch --all --prune
git reset --hard "origin/${DEPLOY_BASE_BRANCH}"

if [ "${ENABLE_MAINTENANCE_MODE}" = "1" ]; then
  echo "→ artisan down"
  ${REMOTE_PHP} artisan down --retry=15 || true
fi

echo "→ composer install (no-dev)"
${REMOTE_PHP} ${REMOTE_COMPOSER} install --no-dev --optimize-autoloader --no-interaction --prefer-dist

echo "→ artisan migrate --force"
${REMOTE_PHP} artisan migrate --force

echo "→ caches"
${REMOTE_PHP} artisan config:cache
${REMOTE_PHP} artisan route:cache
${REMOTE_PHP} artisan view:cache
${REMOTE_PHP} artisan event:cache

echo "→ queue restart"
${REMOTE_PHP} artisan queue:restart || true

if [ "${ENABLE_MAINTENANCE_MODE}" = "1" ]; then
  echo "→ artisan up"
  ${REMOTE_PHP} artisan up
fi

echo "→ done on remote."
REMOTE

ok "Deployed."
echo
echo "Live: https://digiproper.com/"
